/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdSlot {
  'id' : string,
  'placement' : string,
  'targetUrl' : string,
  'enabled' : boolean,
  'imageUrl' : string,
}
export interface Cell { 'value' : Value, 'name' : string }
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface Lineup { 'away' : Array<string>, 'home' : Array<string> }
export interface Match {
  'id' : MatchId,
  'status' : MatchStatus,
  'homeTeam' : string,
  'scorers' : Array<Scorer>,
  'summary' : string,
  'competition' : string,
  'homeScore' : [] | [bigint],
  'kickoff' : Timestamp,
  'awayTeam' : string,
  'awayScore' : [] | [bigint],
  'lineup' : Lineup,
}
export type MatchId = bigint;
export type MatchStatus = { 'upcoming' : null } |
  { 'live' : null } |
  { 'finished' : null };
export interface News {
  'id' : NewsId,
  'title' : string,
  'content' : string,
  'publishedAt' : Timestamp,
  'summary' : string,
  'category' : string,
  'image' : string,
}
export type NewsId = bigint;
export interface Player {
  'id' : PlayerId,
  'teamName' : string,
  'name' : string,
  'stats' : PlayerStats,
  'photo' : string,
  'position' : string,
}
export type PlayerId = bigint;
export interface PlayerStats {
  'assists' : bigint,
  'matches' : bigint,
  'goals' : bigint,
}
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export interface Scorer {
  'teamName' : string,
  'minute' : bigint,
  'playerName' : string,
}
export interface Standing {
  'rows' : Array<StandingRow>,
  'competition' : string,
}
export interface StandingRow {
  'won' : bigint,
  'teamName' : string,
  'played' : bigint,
  'lost' : bigint,
  'position' : bigint,
  'drawn' : bigint,
  'points' : bigint,
}
export interface Team {
  'id' : TeamId,
  'city' : string,
  'logo' : string,
  'name' : string,
  'squad' : Array<string>,
}
export type TeamId = bigint;
export type Timestamp = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'execute' : ActorMethod<[string], Result>,
  'getApiDoc' : ActorMethod<[], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMatch' : ActorMethod<[MatchId], [] | [Match]>,
  'getNews' : ActorMethod<[NewsId], [] | [News]>,
  'getPlayer' : ActorMethod<[PlayerId], [] | [Player]>,
  'getStanding' : ActorMethod<[string], [] | [Standing]>,
  'getTeam' : ActorMethod<[TeamId], [] | [Team]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAdSlots' : ActorMethod<[], Array<AdSlot>>,
  'listCompetitions' : ActorMethod<[], Array<string>>,
  'listMatches' : ActorMethod<
    [[] | [string], [] | [MatchStatus]],
    Array<Match>
  >,
  'listNews' : ActorMethod<[], Array<News>>,
  'listPlayers' : ActorMethod<[[] | [string], [] | [string]], Array<Player>>,
  'listTeams' : ActorMethod<[], Array<Team>>,
  'schema' : ActorMethod<[], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];