/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const MatchId = IDL.Nat;
export const MatchStatus = IDL.Variant({
  'upcoming' : IDL.Null,
  'live' : IDL.Null,
  'finished' : IDL.Null,
});
export const Scorer = IDL.Record({
  'teamName' : IDL.Text,
  'minute' : IDL.Nat,
  'playerName' : IDL.Text,
});
export const Timestamp = IDL.Int;
export const Lineup = IDL.Record({
  'away' : IDL.Vec(IDL.Text),
  'home' : IDL.Vec(IDL.Text),
});
export const Match = IDL.Record({
  'id' : MatchId,
  'status' : MatchStatus,
  'homeTeam' : IDL.Text,
  'scorers' : IDL.Vec(Scorer),
  'summary' : IDL.Text,
  'competition' : IDL.Text,
  'homeScore' : IDL.Opt(IDL.Nat),
  'kickoff' : Timestamp,
  'awayTeam' : IDL.Text,
  'awayScore' : IDL.Opt(IDL.Nat),
  'lineup' : Lineup,
});
export const NewsId = IDL.Nat;
export const News = IDL.Record({
  'id' : NewsId,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'publishedAt' : Timestamp,
  'summary' : IDL.Text,
  'category' : IDL.Text,
  'image' : IDL.Text,
});
export const PlayerId = IDL.Nat;
export const PlayerStats = IDL.Record({
  'assists' : IDL.Nat,
  'matches' : IDL.Nat,
  'goals' : IDL.Nat,
});
export const Player = IDL.Record({
  'id' : PlayerId,
  'teamName' : IDL.Text,
  'name' : IDL.Text,
  'stats' : PlayerStats,
  'photo' : IDL.Text,
  'position' : IDL.Text,
});
export const StandingRow = IDL.Record({
  'won' : IDL.Nat,
  'teamName' : IDL.Text,
  'played' : IDL.Nat,
  'lost' : IDL.Nat,
  'position' : IDL.Nat,
  'drawn' : IDL.Nat,
  'points' : IDL.Nat,
});
export const Standing = IDL.Record({
  'rows' : IDL.Vec(StandingRow),
  'competition' : IDL.Text,
});
export const TeamId = IDL.Nat;
export const Team = IDL.Record({
  'id' : TeamId,
  'city' : IDL.Text,
  'logo' : IDL.Text,
  'name' : IDL.Text,
  'squad' : IDL.Vec(IDL.Text),
});
export const AdSlot = IDL.Record({
  'id' : IDL.Text,
  'placement' : IDL.Text,
  'targetUrl' : IDL.Text,
  'enabled' : IDL.Bool,
  'imageUrl' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMatch' : IDL.Func([MatchId], [IDL.Opt(Match)], ['query']),
  'getNews' : IDL.Func([NewsId], [IDL.Opt(News)], ['query']),
  'getPlayer' : IDL.Func([PlayerId], [IDL.Opt(Player)], ['query']),
  'getStanding' : IDL.Func([IDL.Text], [IDL.Opt(Standing)], ['query']),
  'getTeam' : IDL.Func([TeamId], [IDL.Opt(Team)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAdSlots' : IDL.Func([], [IDL.Vec(AdSlot)], ['query']),
  'listCompetitions' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'listMatches' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(MatchStatus)],
      [IDL.Vec(Match)],
      ['query'],
    ),
  'listNews' : IDL.Func([], [IDL.Vec(News)], ['query']),
  'listPlayers' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [IDL.Vec(Player)],
      ['query'],
    ),
  'listTeams' : IDL.Func([], [IDL.Vec(Team)], ['query']),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const MatchId = IDL.Nat;
  const MatchStatus = IDL.Variant({
    'upcoming' : IDL.Null,
    'live' : IDL.Null,
    'finished' : IDL.Null,
  });
  const Scorer = IDL.Record({
    'teamName' : IDL.Text,
    'minute' : IDL.Nat,
    'playerName' : IDL.Text,
  });
  const Timestamp = IDL.Int;
  const Lineup = IDL.Record({
    'away' : IDL.Vec(IDL.Text),
    'home' : IDL.Vec(IDL.Text),
  });
  const Match = IDL.Record({
    'id' : MatchId,
    'status' : MatchStatus,
    'homeTeam' : IDL.Text,
    'scorers' : IDL.Vec(Scorer),
    'summary' : IDL.Text,
    'competition' : IDL.Text,
    'homeScore' : IDL.Opt(IDL.Nat),
    'kickoff' : Timestamp,
    'awayTeam' : IDL.Text,
    'awayScore' : IDL.Opt(IDL.Nat),
    'lineup' : Lineup,
  });
  const NewsId = IDL.Nat;
  const News = IDL.Record({
    'id' : NewsId,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'publishedAt' : Timestamp,
    'summary' : IDL.Text,
    'category' : IDL.Text,
    'image' : IDL.Text,
  });
  const PlayerId = IDL.Nat;
  const PlayerStats = IDL.Record({
    'assists' : IDL.Nat,
    'matches' : IDL.Nat,
    'goals' : IDL.Nat,
  });
  const Player = IDL.Record({
    'id' : PlayerId,
    'teamName' : IDL.Text,
    'name' : IDL.Text,
    'stats' : PlayerStats,
    'photo' : IDL.Text,
    'position' : IDL.Text,
  });
  const StandingRow = IDL.Record({
    'won' : IDL.Nat,
    'teamName' : IDL.Text,
    'played' : IDL.Nat,
    'lost' : IDL.Nat,
    'position' : IDL.Nat,
    'drawn' : IDL.Nat,
    'points' : IDL.Nat,
  });
  const Standing = IDL.Record({
    'rows' : IDL.Vec(StandingRow),
    'competition' : IDL.Text,
  });
  const TeamId = IDL.Nat;
  const Team = IDL.Record({
    'id' : TeamId,
    'city' : IDL.Text,
    'logo' : IDL.Text,
    'name' : IDL.Text,
    'squad' : IDL.Vec(IDL.Text),
  });
  const AdSlot = IDL.Record({
    'id' : IDL.Text,
    'placement' : IDL.Text,
    'targetUrl' : IDL.Text,
    'enabled' : IDL.Bool,
    'imageUrl' : IDL.Text,
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMatch' : IDL.Func([MatchId], [IDL.Opt(Match)], ['query']),
    'getNews' : IDL.Func([NewsId], [IDL.Opt(News)], ['query']),
    'getPlayer' : IDL.Func([PlayerId], [IDL.Opt(Player)], ['query']),
    'getStanding' : IDL.Func([IDL.Text], [IDL.Opt(Standing)], ['query']),
    'getTeam' : IDL.Func([TeamId], [IDL.Opt(Team)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAdSlots' : IDL.Func([], [IDL.Vec(AdSlot)], ['query']),
    'listCompetitions' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'listMatches' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(MatchStatus)],
        [IDL.Vec(Match)],
        ['query'],
      ),
    'listNews' : IDL.Func([], [IDL.Vec(News)], ['query']),
    'listPlayers' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Vec(Player)],
        ['query'],
      ),
    'listTeams' : IDL.Func([], [IDL.Vec(Team)], ['query']),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };